template_dir: /resources/views
template_ext: phtml
translation_dir: /resources/translations
public_dir: includes
media_dir: server/files

fallback:
    language: &lang ru

language: *lang

db_host: localhost
db_name: test
db_user: root
db_password: 

csrf_lifetime: 3600