home:
    path: /
    controller: Home
    action: index

news:
    path: /news
    controller: News
    action: all
    method: [get]

article_show:
    path: /news/(?'id'\d+)
    generator: /news/{id}
    controller: News
    action: show
    method: [get]

article_update:
    path: /news/(?'id'\d+)
    generator: /news/{id}
    controller: News
    action: update
    method: [post]

article_remove:
    path: /news/(?'id'\d+)/delete
    generator: /news/{id}/delete
    controller: News
    action: remove
    method: [post]

article_edit:
    path: /news/(?'id'\d+)/edit
    generator: /news/{id}/edit
    controller: News
    action: edit

article_add:
    path: /news/add
    controller: News
    action: add

article_post:
    path: /news
    controller: News
    action: post
    method: [post]

gallery_show:
    path: /gallery
    controller: Gallery
    action: all
    method: [get]

gallery_post:
    path: /gallery
    controller: Gallery
    action: post
    method: [post, put]

gallery_server:
    path: /server/index.php

login:
    path: /login
    controller: Home
    action: login
    method: [post]